%%%%code of phase retrieval with boost DC algorithm 
%read me 
%there are two masks

%the first is in Demo_phase_Retrieval/TVPR_SISC_h_finaltest
%run demo 
%the results are also in there
%compare means mask ratio 50, the 30 is not test in this paper
%all the test are mask ratio 50, and 10, 30 are the noise level
%comp are zoomed images which displayed in the paper

%the DCP mask is in codesphaseretrieval
%add phasepack-matlab-master and PR-ADMM in the path
%the demo is in PR-ADMM
%demo10 and demo 30 are the demo with noise level 10 and 30
%we compare RAAR RAF RWF TAF CDA TWF with the initial 
%point generated by ER
%the codes of compared algorithm are in phasepack-matlab-master
