%%%%code of phase retrieval with boost DC algorithm 
% This is the code of the paper 
% 'Finding Robust Minimizer for Non-convex Phase Retrieval, 
% Tingting Wu and Chaoyan Huang and Xiaoyu Gu and Jianwei Niu and Tieyong Zeng, Inverse Problems and Imaging, 2023'.
% read me 

% the DCP mask is in codesphaseretrieval
% add phasepack-matlab-master and PR-ADMM in the path
% the demo is in PR-ADMM
% demo10 and demo 30 are the demo with noise level 10 and 30
% we compare RAAR RAF RWF TAF CDA TWF with the initial 
% point generated by ER
% the codes of compared algorithm are in phasepack-matlab-master
