% -------------------------------------------------------------------
%  Generated by MATLAB on 21-Jun-2021 10:41:10
%  MATLAB version: 9.8.0.1380330 (R2020a) Update 2
% -------------------------------------------------------------------
saveVarsMat = load('readme.mat');

A = saveVarsMat.A; % <1x1 function_handle> 不支持的类

At = saveVarsMat.At; % <1x1 function_handle> 不支持的类

AtA = saveVarsMat.AtA; % <1x1 function_handle> 不支持的类

AtAER = saveVarsMat.AtAER; % <500x500 double> 元素太多

L = 2;

Masks = saveVarsMat.Masks; % <500x500x2 double> 元素太多

PM = saveVarsMat.PM; % <1x1 function_handle> 不支持的类

PS = saveVarsMat.PS; % <1x1 function_handle> 不支持的类

Params = struct;
Params.n1 = 500;
Params.n2 = 500;

ParamsTV = struct;
ParamsTV.L = 2;
ParamsTV.gamma = 5000;
ParamsTV.lambda = 2000;
ParamsTV.elp = 0.0001;
ParamsTV.flag = 1;
ParamsTV.const = 1;
ParamsTV.maxDCA = 20;
ParamsTV.nIter = 15;
ParamsTV.tol = 1E-10;
ParamsTV.oit = 1;
ParamsTV.tau = 1;
ParamsTV.HIO_iter = 50;

SNR_twf = 23.536312444763929;

W = saveVarsMat.W; % <500x500x2 double> 元素太多

X = saveVarsMat.X; % <500x500 double> 元素太多

YGauss = saveVarsMat.YGauss; % <500x500x2 double> 元素太多

lambdaWF = 1200;

ll = 2;

n1 = 500;

n2 = 500;

namestr = '18';

opts = struct;
opts.algorithm = 'rwf';
opts.initMethod = 'optimal';
opts.tol = 0.001;
opts.verbose = 2;
opts.isComplex = true;
opts.isNonNegativeOnly = false;
opts.maxIters = 10000;
opts.maxTime = 300;
opts.recordTimes = true;
opts.recordMeasurementErrors = 0;
opts.recordReconErrors = 0;
opts.recordResiduals = 1;
opts.label = [];
opts.xt = [];
opts.customAlgorithm = [];
opts.customx0 = [];
opts.initAngle = [];
opts.eta = 0.9;
opts.reweightPeriod = 20;
opts.searchMethod = 'steepestDescent';
opts.betaChoice = 'HS';
opts.alpha_lb = 0.1;
opts.alpha_ub = 5;
opts.alpha_h = 6;
opts.truncationPeriod = 20;

outs_twf = saveVarsMat.outs_twf; % <1x1 struct> outs_twf.solveTimes 中的元素太多

sigma = 10;

snr_ini = 24.027570974445712;

stanstr = 'tif';

temp = saveVarsMat.temp; % <500x500x2 double> 元素太多

u0 = saveVarsMat.u0; % <500x500 double> 元素太多

u_TWF = saveVarsMat.u_TWF; % <500x500 double> 元素太多

x = saveVarsMat.x; % <500x500 double> 元素太多

clear saveVarsMat;
